/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface FlagsInterface extends ethers.utils.Interface {
  functions: {
    "MULTI_SEND()": FunctionFragment;
    "PROXY_WITH_SENDER()": FunctionFragment;
    "REVERT_IF_EXTERNAL_FAIL()": FunctionFragment;
    "SEND_EXTERNAL_CALL_GAS_LIMIT()": FunctionFragment;
    "SEND_HASHED_DATA()": FunctionFragment;
    "UNWRAP_ETH()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MULTI_SEND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROXY_WITH_SENDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REVERT_IF_EXTERNAL_FAIL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEND_EXTERNAL_CALL_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEND_HASHED_DATA",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNWRAP_ETH",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MULTI_SEND", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PROXY_WITH_SENDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REVERT_IF_EXTERNAL_FAIL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEND_EXTERNAL_CALL_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEND_HASHED_DATA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "UNWRAP_ETH", data: BytesLike): Result;

  events: {};
}

export class Flags extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FlagsInterface;

  functions: {
    MULTI_SEND(overrides?: CallOverrides): Promise<[BigNumber]>;

    PROXY_WITH_SENDER(overrides?: CallOverrides): Promise<[BigNumber]>;

    REVERT_IF_EXTERNAL_FAIL(overrides?: CallOverrides): Promise<[BigNumber]>;

    SEND_EXTERNAL_CALL_GAS_LIMIT(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    SEND_HASHED_DATA(overrides?: CallOverrides): Promise<[BigNumber]>;

    UNWRAP_ETH(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  MULTI_SEND(overrides?: CallOverrides): Promise<BigNumber>;

  PROXY_WITH_SENDER(overrides?: CallOverrides): Promise<BigNumber>;

  REVERT_IF_EXTERNAL_FAIL(overrides?: CallOverrides): Promise<BigNumber>;

  SEND_EXTERNAL_CALL_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  SEND_HASHED_DATA(overrides?: CallOverrides): Promise<BigNumber>;

  UNWRAP_ETH(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    MULTI_SEND(overrides?: CallOverrides): Promise<BigNumber>;

    PROXY_WITH_SENDER(overrides?: CallOverrides): Promise<BigNumber>;

    REVERT_IF_EXTERNAL_FAIL(overrides?: CallOverrides): Promise<BigNumber>;

    SEND_EXTERNAL_CALL_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    SEND_HASHED_DATA(overrides?: CallOverrides): Promise<BigNumber>;

    UNWRAP_ETH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    MULTI_SEND(overrides?: CallOverrides): Promise<BigNumber>;

    PROXY_WITH_SENDER(overrides?: CallOverrides): Promise<BigNumber>;

    REVERT_IF_EXTERNAL_FAIL(overrides?: CallOverrides): Promise<BigNumber>;

    SEND_EXTERNAL_CALL_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    SEND_HASHED_DATA(overrides?: CallOverrides): Promise<BigNumber>;

    UNWRAP_ETH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    MULTI_SEND(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PROXY_WITH_SENDER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REVERT_IF_EXTERNAL_FAIL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SEND_EXTERNAL_CALL_GAS_LIMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SEND_HASHED_DATA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UNWRAP_ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
