/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IDeBridgeTokenDeployerInterface extends ethers.utils.Interface {
  functions: {
    "deployAsset(bytes32,string,string,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deployAsset",
    values: [BytesLike, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployAsset",
    data: BytesLike
  ): Result;

  events: {
    "DeBridgeTokenDeployed(address,string,string,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeBridgeTokenDeployed"): EventFragment;
}

export type DeBridgeTokenDeployedEvent = TypedEvent<
  [string, string, string, number] & {
    asset: string;
    name: string;
    symbol: string;
    decimals: number;
  }
>;

export class IDeBridgeTokenDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IDeBridgeTokenDeployerInterface;

  functions: {
    deployAsset(
      _debridgeId: BytesLike,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deployAsset(
    _debridgeId: BytesLike,
    _name: string,
    _symbol: string,
    _decimals: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deployAsset(
      _debridgeId: BytesLike,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DeBridgeTokenDeployed(address,string,string,uint8)"(
      asset?: null,
      name?: null,
      symbol?: null,
      decimals?: null
    ): TypedEventFilter<
      [string, string, string, number],
      { asset: string; name: string; symbol: string; decimals: number }
    >;

    DeBridgeTokenDeployed(
      asset?: null,
      name?: null,
      symbol?: null,
      decimals?: null
    ): TypedEventFilter<
      [string, string, string, number],
      { asset: string; name: string; symbol: string; decimals: number }
    >;
  };

  estimateGas: {
    deployAsset(
      _debridgeId: BytesLike,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployAsset(
      _debridgeId: BytesLike,
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
