/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ISignatureVerifierInterface extends ethers.utils.Interface {
  functions: {
    "submit(bytes32,bytes,uint8)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "submit",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;

  events: {
    "Confirmed(bytes32,address)": EventFragment;
    "DeployConfirmed(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Confirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployConfirmed"): EventFragment;
}

export type ConfirmedEvent = TypedEvent<
  [string, string] & { submissionId: string; operator: string }
>;

export type DeployConfirmedEvent = TypedEvent<
  [string, string] & { deployId: string; operator: string }
>;

export class ISignatureVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ISignatureVerifierInterface;

  functions: {
    submit(
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  submit(
    _submissionId: BytesLike,
    _signatures: BytesLike,
    _excessConfirmations: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    submit(
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Confirmed(bytes32,address)"(
      submissionId?: null,
      operator?: null
    ): TypedEventFilter<
      [string, string],
      { submissionId: string; operator: string }
    >;

    Confirmed(
      submissionId?: null,
      operator?: null
    ): TypedEventFilter<
      [string, string],
      { submissionId: string; operator: string }
    >;

    "DeployConfirmed(bytes32,address)"(
      deployId?: null,
      operator?: null
    ): TypedEventFilter<
      [string, string],
      { deployId: string; operator: string }
    >;

    DeployConfirmed(
      deployId?: null,
      operator?: null
    ): TypedEventFilter<
      [string, string],
      { deployId: string; operator: string }
    >;
  };

  estimateGas: {
    submit(
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    submit(
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
